folio-org/ui-courses

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20200110T211826

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20200217T172736

- package.json
See [UICR-34](https://issues.folio.org/browse/UICR-34)
> Remove extra spaces in permission value

- translations/ui-courses/ar.json
- translations/ui-courses/ca.json
- translations/ui-courses/da.json
- translations/ui-courses/de.json
- translations/ui-courses/en_GB.json
- translations/ui-courses/en_SE.json
- translations/ui-courses/en_US.json
- translations/ui-courses/es.json
- translations/ui-courses/es_419.json
- translations/ui-courses/es_ES.json
- translations/ui-courses/fr.json
- translations/ui-courses/fr_FR.json
- translations/ui-courses/he.json
- translations/ui-courses/hu.json
- translations/ui-courses/it_IT.json
- translations/ui-courses/ja.json
- translations/ui-courses/pt_BR.json
- translations/ui-courses/pt_PT.json
- translations/ui-courses/ru.json
- translations/ui-courses/ur.json
- translations/ui-courses/zh_CN.json
- translations/ui-courses/zh_TW.json
> Update translation strings as of 20200220T141728

- translations/ui-courses/ar.json
- translations/ui-courses/ca.json
- translations/ui-courses/da.json
- translations/ui-courses/de.json
- translations/ui-courses/en_GB.json
- translations/ui-courses/en_SE.json
- translations/ui-courses/en_US.json
- translations/ui-courses/es.json
- translations/ui-courses/es_419.json
- translations/ui-courses/es_ES.json
- translations/ui-courses/fr.json
- translations/ui-courses/fr_FR.json
- translations/ui-courses/he.json
- translations/ui-courses/hu.json
- translations/ui-courses/it_IT.json
- translations/ui-courses/ja.json
- translations/ui-courses/pt_BR.json
- translations/ui-courses/pt_PT.json
- translations/ui-courses/ru.json
- translations/ui-courses/ur.json
- translations/ui-courses/zh_CN.json
- translations/ui-courses/zh_TW.json
> Update translation strings as of 20200309T000645

- translations/ui-courses/ru.json
> Update translation strings as of 20200316T134017

- translations/ui-courses/ru.json
> Update translation strings as of 20200317T123814

- translations/ui-courses/ar.json
- translations/ui-courses/ca.json
- translations/ui-courses/da.json
- translations/ui-courses/de.json
- translations/ui-courses/en_GB.json
- translations/ui-courses/en_SE.json
- translations/ui-courses/en_US.json
- translations/ui-courses/es.json
- translations/ui-courses/es_419.json
- translations/ui-courses/es_ES.json
- translations/ui-courses/fr.json
- translations/ui-courses/fr_FR.json
- translations/ui-courses/he.json
- translations/ui-courses/hu.json
- translations/ui-courses/it_IT.json
- translations/ui-courses/ja.json
- translations/ui-courses/pt_BR.json
- translations/ui-courses/pt_PT.json
- translations/ui-courses/ru.json
- translations/ui-courses/ur.json
- translations/ui-courses/zh_CN.json
- translations/ui-courses/zh_TW.json
> Update translation strings as of 20200406T162815

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20200519T123842

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20200526T141248

- translations/ui-courses/ru.json
> Update translation strings as of 20200602T151309

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20200604T202430

- translations/ui-courses/ru.json
> Update translation strings as of 20200615T161518

- translations/ui-courses/ar.json
- translations/ui-courses/ca.json
- translations/ui-courses/da.json
- translations/ui-courses/de.json
- translations/ui-courses/en_GB.json
- translations/ui-courses/en_SE.json
- translations/ui-courses/en_US.json
- translations/ui-courses/es.json
- translations/ui-courses/es_419.json
- translations/ui-courses/es_ES.json
- translations/ui-courses/fr.json
- translations/ui-courses/fr_FR.json
- translations/ui-courses/he.json
- translations/ui-courses/hu.json
- translations/ui-courses/it_IT.json
- translations/ui-courses/ja.json
- translations/ui-courses/pt_BR.json
- translations/ui-courses/pt_PT.json
- translations/ui-courses/ru.json
- translations/ui-courses/ur.json
- translations/ui-courses/zh_CN.json
- translations/ui-courses/zh_TW.json
> Update translation strings as of 20200721T202356

- translations/ui-courses/it_IT.json
> Update translation strings as of 20201013T203429

- translations/ui-courses/fr_FR.json
> Update translation strings as of 20201119T214636

- translations/ui-courses/ja.json
> Update translation strings as of 20201124T212804

- src/components/ReserveForm/ReserveForm.js
- src/components/ViewCourse/sections/ViewCourseData.js
What it says on the tin. We're just using the standard `ViewMetaData` component plopped into the first accordion.
> UICR-116 & UICR-117: show record metadata when viewing Course or Reserve

- CHANGELOG.md
- package.json
> Fix visibility of permissions and canonicalize upper/lower case.

- src/components/ViewCourse/sections/ViewCourseCrosslistings.js
Completely missed the bullet point in the [jira description](https://issues.folio.org/browse/UXPROD-2772) asking for this.
> Show numberOfStudents in crosslisted courses

- package.json
- src/components/CourseForm/CourseForm.js
- src/components/Courses.js
- src/routes/EditReserveRoute.js
- translations/ui-courses/en.json
Had to break up the `.write` perms [provided by mod-courses](https://github.com/folio-org/mod-courses/blob/master/descriptors/ModuleDescriptor-template.json) so that I could separate out the post, put and delete perms.
> UICR-141: Fixed course permissions

- Jenkinsfile
- package.json
- src/components/Courses.js
- UICR-133: Added translation compilation
- UICR-135: Use new versions of find-user plugin
- Disable sorting for headers where the backend doesn't properly sort that attribute
> UICR-133 UICR-135 Bug Fixes

- CHANGELOG.md
- src/components/ViewCourse/ViewCourse.js
- src/index.js
- src/routes/NoteCreateRoute.js
- src/routes/NoteEditRoute.js
- src/routes/NoteViewRoute.js
- src/util/getReferredEntityData.js
- src/util/retrieveNoteReferredEntityDataFromLocationState.js
- translations/ui-courses/en.json
Implemented Notes helper module within Courses.
Issue: [UICR-126](https://issues.folio.org/browse/UICR-126)
Also, change in stripes-smart-components was required ([STSMACOM-524](https://issues.folio.org/browse/STSMACOM-524))
> UICR-126: Courses: Implement Notes for Courses

- CHANGELOG.md
- src/components/Courses.js
- translations/ui-courses/en.json
Implemented `<ColumnManager>` for managing visible columns in the results list.
Issue: [UICR-132](https://issues.folio.org/browse/UICR-132)
> UICR-132: Results List | Apply Results list column chooser

- CHANGELOG.md
- src/components/Reserves.js
Implemented `<ColumnManager>` for managing visible columns in the Reserves results list.
Issue: [UICR-146](https://issues.folio.org/browse/UICR-146)
> UICR-146: Course Reserves List | Apply Results list column chooser

- CHANGELOG.md
- package.json
Added additional permissions in Courses
[UICR-157](https://issues.folio.org/browse/UICR-157)
> UICR-157: Add additional permissions in Courses

- CHANGELOG.md
- package.json
- src/index.js
https://issues.folio.org/browse/UICR-154
> UICR-154: Remove react-hot-loader

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
> Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/util/withOkapiKy.js
> Leverage cookie-based authentication in all API requests

- CHANGELOG.md
- package.json
- src/settings/CopyrightStatusSettings.js
- src/settings/CourseTypeSettings.js
- src/settings/DepartmentSettings.js
- src/settings/DisplaySettingsForm.js
- src/settings/ProcessingStatusSettings.js
- src/settings/TermSettings.js
- translations/ui-courses/en.json
Also, the relevant UI elements are disabled or removed for users who lack relevant permissions.
Fixes UICR-181.
> New permission `ui-courses.view-settings` to view but not edit settings

- CHANGELOG.md
- src/components/CourseForm/sections/CourseFormInfo.js
- src/components/CourseForm/sections/CourseFormListing.js
Department and term.
Fixes UICR-93.
> Required course fields now perform front-end validation

- CHANGELOG.md
- src/components/ViewCourse/VCAccordion.js
- src/components/ViewCourse/ViewCourse.js
- translations/ui-courses/en.json
- translations/ui-courses/en_US.json
> When viewing a course, show number of reserves before list

- CHANGELOG.md
- src/settings/CopyrightStatusSettings.js
- src/settings/CourseTypeSettings.js
- src/settings/DepartmentSettings.js
- src/settings/ProcessingStatusSettings.js
- src/settings/RoleSettings.js
- src/settings/TermSettings.js
- translations/ui-courses/en.json
https://folio-org.atlassian.net/browse/UICR-163
Here we updated props for `ControlledVocab`. Also, added new translations
> UICR-163: Provide local translations to ControlledVocab

- CHANGELOG.md
- src/index.js
- translations/ui-courses/en.json
After this PR merged, new item will be added to NavList. After clicking it will redirect user to default courses search. Refs [UICR-166](https://folio-org.atlassian.net/browse/UICR-166)
> UICR-166 App Context menu | Add new option | Courses app search

- src/components/Reserves.js
- src/components/ReservesSearchPane.js
https://folio-org.atlassian.net/browse/UICR-174
Here we add a fix for the collapse icon in `Reserves` tab
> UICR-174: Courses app: Replace collapse pane icons

- CHANGELOG.md
- src/components/DeleteCourseModal.js
- translations/ui-courses/en.json
- translations/ui-courses/en_US.json
> Green toast on successful course deletion.

- CHANGELOG.md
- src/components/InstructorForm.js
- src/components/ReserveForm/ReserveForm.js
- src/components/ViewCourse/sections/ViewCourseReserves.js
> Remove use of italics in three places in the UI.

- src/components/DeleteCourseModal.js
Fixes a late-appearing and catastrophic part of UICR-207.
> DeleteCourseModal always renders

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/routes/CourseRoute.js
> Extend limit of reserves for which status is fetched from 20 to 100
