folio-org/ui-courses

package.json
The scope of the story is to migrate to the new version of:
Changes:
1. {{item.status.name}} has restricted to the following values:
* Available
* Awaiting pickup
* Awaiting delivery
* Checked out
* In process
* In transit
* Missing
* On order
* Paged
* Withdrawn
* Declared lost
2. *Item.status* and *item.status.name* are required now, no defaulting available anymore;
3. Array *item.copyNumbers* converted to a single value *copyNumber*;
4. Item.status.date is read-only field now and has date-time formatting now ("yyyy-MM-dd'T'HH:mm:ss.SSS+0000").
=> UICR-20: Migrate to item-storage v8.0.

CHANGELOG.md, package.json, src/components/CourseForm/sections/CourseFormInfo.js, src/components/InstructorForm.js
`stripes-util` exports should be consumed via `@folio/stripes/util` and
a peer-dep on `@folio/stripes` rather than a direct dep on
`@folio/stripes-util`.
=> correctly import `required`

Jenkinsfile, README.md
Verify the new alternative path to LCOV info. See [FOLIO-2682](https://issues.folio.org/browse/FOLIO-2682)
And testing Sonarqube on merge to master.
=> FOLIO-2682 sonarqube alternative LCOV path

CHANGELOG.md, Jenkinsfile, package.json
When the `test` and `postinstall` hooks that are herein renamed with the
`-UNUSED` suffix are present, it causes the `platform-complete#snapshot`
build to fail in a very odd way. Specifically, it causes ui-courses to
not see any of the modules hoisted/provided by the platform. When it
comes to those modules ui-courses is supposed to receive via
peer-dependencies, this is problematic because they are not allowed to
be duplicated in the bundle.
I have no explanation for _why_ this is happening. I can only tell
you that when these two lines are present it _is_ happening and it
breaks the build. Running theory: `test` and `postinstall` are somehow
special to yarn, for definitions of "special" where it means "The battle
of stripes, 2020 ... your build turned upside down!"
=> rename script entries that break platform-complete

.stripesclirc.js
This was one lingering file. The others were done in PR #74 
@MikeTaylor The "tapes" still refer to the old now-defunct hostname. Leaving that part to you.
=> FOLIO-2706 Use FQDN .dev.folio.org

CHANGELOG.md, package.json, src/index.js
Update peer deps for compatibility with `@folio/stripes` `v5`
compatibility, including `stripes` itself, `react-router` `v5`, and
`react-intl` `v5`.
Refs [UICR-108](https://issues.folio.org/browse/UICR-108), [UICR-109](https://issues.folio.org/browse/UICR-108)
=> UICR-108 update peer-deps for stripes v5 compat

CHANGELOG.md, package.json, src/components/ReserveForm/sections/ReserveFormInfo.js, src/settings/TermSettings.js
Pass the `usePortal` prop to `<Datepicker>` to prevent its display from
being clipped when the container window is narrow.
Refs [UICR-103](https://issues.folio.org/browse/UICR-103)
=> UICR-103 avoid clipping Datepicker display

CHANGELOG.md, package.json, src/components/Course.js, src/components/CourseForm/CourseForm.js, src/components/InstructorForm.js, src/components/LoadingPaneSet.js, src/components/ReserveForm/ReserveForm.js, src/components/ViewCourse/sections/AddFastAddReserve.js, src/components/ViewCourse/sections/AddReserve.js, src/components/ViewCourse/sections/ViewCourseData.js, src/components/ViewCourse/sections/ViewCourseInstructors.js, src/components/ViewCourse/sections/ViewCourseReserves.js, src/components/ViewCourse/sections/ViewCourseTerm.js, src/util/getOptions.js, translations/ui-courses/en.json
UICR-91: Adds the ability to "Fast Add" new Inventory records as course reserves. 
If you want to add a course reserve that isn't in Inventory, there's a new "Fast Add" button that uses a `create-inventory-records` plugin to display a Fast Add modal. Said plugins allow a user to create an instance, holding and item record all at once without leaving the current app. This plugin type is already used in ui-checkout and ui-inventory itself. Upon saving the new records, the item is added as a reserve to the course being viewed.
While working on this, the best UX wasn't completely clear to me or Duke staff I dragged into a Zoom meeting, so I've gone ahead with a side-by-side approach in the hopes that it properly distinguishes what the two different ways of adding reserves are and what button …
=> UICR-91: Fast Add reserves

src/components/Courses.js, src/components/CoursesSearchPane.js, src/components/Reserves.js, src/components/ReservesSearchPane.js
Patterned off of [ui-users](https://github.com/folio-org/ui-users/blob/master/src/views/UserSearch/UserSearch.js).
When we're gonna fire off a text search, we set a `searchPending` flag in state so we know that the `source` activity was triggered by a user's search. When that `source` activity settles (isn't `pending`), we manually `.focus()` the pane title via a ref.
(Also nuked an ariaLabel prop-type error while I was looking at the code)
=> UICR-111: Focus Results pane when search has hits

package.json
It should have remained as an optional dep. I think npm autoadded it while I was working on PR #114
=> Removed plugin-create-inventory-records from deps

CHANGELOG.md, src/components/ViewCourse/sections/ViewCourseData.js
Metadata is handled confusingly on our records. It's tracked
separately for `course`, `courseListing`, `instructor`, and `reserve`
records. This means that to get the last time the "Course" was
updated, we need to run through all of that metadata and see
which is latest. Sure, possible, but the final wrinkle is actually
when an instructor or reserve is removed from a courseListing.
In that case, the course or courseListing's metadata are not
updated, so the lastUpdated date can actually _go backwards
in time._ Woof. So, we're backing out this functionality until the
backend changes the way it handles metadata.
The SIG was understandably confused by how everything worked so requested this be backed out in UICR-116.
=> UICR-116: Removed metadata when viewing course

CHANGELOG.md, package.json, src/components/CourseForm/sections/CourseFormInfo.js, src/components/ViewCourse/sections/ViewCourseData.js, translations/ui-courses/en.json
This uses https://github.com/folio-org/mod-courses/pull/113 to view/edit a course's `numberOfStudents`.
Note i've also popped a tweak to the version of eslint being used. Folio generally uses v6 and having multiple versions available can confuse some package managers so I've bumped it back for workspace-management sanity.
=> UICR-128: Added ability to view/edit course's numberOfStudents

src/settings/DisplaySettings.js
On a new installation, the `.value` doesn't exist yet, so optionally chain into it and null coalesce it into a JSON object if it doesn't exist.
=> UICR-131: Added fallback before parsing if setting isn't defined

CHANGELOG.md, package.json, src/components/ViewCourse/sections/AddReserve.js
Also, in passing: minor reformatting of the package file to minimise diffs when using `yarn add`.
=> UICR-134 Repair regression in duplicate-reserve error message 

src/components/Courses.js
Maintain support for date strings, but also support the datetime strings that are created when the UI is used to create terms.
=> UICR-137: Handle term dates that are datetime strings

package.json, src/routes/AddInstructorRoute.js, src/routes/CreateCourseRoute.js, src/routes/CrosslistCourseRoute.js, src/routes/EditCourseRoute.js, src/routes/EditInstructorRoute.js
This tweaks the perm checks that are done in route handlers. https://github.com/folio-org/ui-courses/pull/141 broke up the perm sets so `.write` is no longer an effective perm to use for gating access to these routes.
Additionally, the instructor form routes appeared to be checking an unrelated permission so I changed them to check the instructor mutation permissions instead.
=> UICR-141: Fixed permission gates on routes

src/components/Reserves.js
The Reserves MCL launches right into the Edit form which then shows a user a "you don't have the perms" error if they only have read perms. Changed it so that they just aren't able to nav to the form, since per Folio UX guidelines we should generally avoid displaying things users can't do.
=> Made Reserves MCL uninteractive if user lacks the edit perms

package.json, src/settings/TermSettings.js
Noticed we could knock this one out fairly quickly, now that [`EditableList` supports redux-form and react-final-form](https://github.com/folio-org/stripes-smart-components/blob/e86c711c49033ad162ac7ac21b8fedda2d526257/lib/EditableList/EditableListFinalForm.js) and `ControlledVocab` lets us pass-through the `formType` into it.
=> UICR-92: Removed dependency on redux-form

package.json
Add the item-storage 9.0 dependency for optimistic locking.
No code change is needed because ui-courses doesn't directly
PUT to item-storage, it calls
/coursereserves/courselistings/{listing_id}/reserves/{reserve_id}
that does the job.
ui-courses GETs item-storage/items/:{itemId} but this is used
for display only and the new `_version` property is not used
and doesn't affect ui-courses.
=> UICR-138: Add item-storage 9.0 optimistic locking dependency

src/components/Courses.css
After the `postcss` changes in [STCOM-863](https://issues.folio.org/browse/STCOM-863) / [PR 1598](https://github.com/folio-org/stripes-components/pull/1598), 
we uncovered some previously unnoticed syntax errors.
=> use correct syntax (pursuant to STCOM-863)

CHANGELOG.md, package.json
mod-inventory-storage has new major interface versions:
instance-storage 9.0
holdings-storage 6.0
item-storage 10.0
ui-courses uses only item-storage, not the other two.
ui-courses is not affected because the incompatible change is in the DELETE all APIs only.
Only the okapiInterfaces need to be bumped in package.json.
=> UIPCIR-43: item-storage 10.0

CHANGELOG.md, package.json
refactor psets away from backend ".all" permissions
https://issues.folio.org/browse/UICR-150
=> UICR-150 - refactor psets away from backend ".all" permissions

CHANGELOG.md, package.json
Update `@folio/plugin-create-inventory-records` dependency version to one compatible with our Stripes version.
Fixes UICR-169.
=> Update plugin dependency

CHANGELOG.md, src/util/renderFilter.js
Filtering of candidate values for location filter (and other search filters) is no longer left-anchored, but matches anywhere within the candidate values, emulating the behaviour of the Inventory app.
Fixes UICR-160.
=> Unanchored filtering of candidate filter values

src/components/CourseForm/CourseForm.js, src/components/InstructorForm.js, src/components/ReserveForm/ReserveForm.js
Use `PropTypes.shape`, which is a thing, instead of `PropTypes.PropTypes.shape`, which is not. Interestingly, neither yarn nor lint tripped on this, but experimenting with pnpm it showed up immediately as an unrecoverable error.
Refs [UICR-202](https://folio-org.atlassian.net/browse/UICR-202)
=> UICR-202 PropTypes fixup

CHANGELOG.md, src/components/CourseForm/CourseForm.js, src/routes/EditCourseRoute.js
This is intended to prevent orphan course-listings from lying around, preventing the deletion of terms that are still in use by them (see UICR-203). If the deletion of course-listing fails, we ignore that failure, as it's likely due to the existence of another course using it.
This works so far as it goes, but it turns out that course-listing deletion also fails if there are instructors assigned, and that these need to be deleted first. Since I'm not sure whether that ought to be the UI's responsibility, I'm ignoring it for now and committing the present version.
Fixes UICR-206.
=> When deleting a course, also delete its courselisting 

src/index.js
In scope of PR https://github.com/folio-org/ui-courses/pull/280 1 line was missed. After this PR merged menu will be closed after click.
=> UICR-166 close menu once item is clicked

CHANGELOG.md, package.json
Update plugin dependencies to allow
* `@folio/plugin-find-user` ^8.0.0
* `@folio/plugin-create-inventory-records` ^6.0.0
(as well as previously acceptable versions).
=> [UICR-222] Update plugin dependencies for Sunflower

CHANGELOG.md, src/routes/CoursesRoute.js, src/routes/ReservesRoute.js
Since release v6.1.1, when listing all courses or reserves (as opposed to those matching a query), sorting was not performed. This is no longer the case.
=> [UICR-225] Sort even when query is not specified.

CHANGELOG.md, src/settings/CopyrightStatusSettings.js, src/settings/CourseTypeSettings.js, src/settings/DepartmentSettings.js, src/settings/ProcessingStatusSettings.js, src/settings/TermSettings.js
When a user has the permission `ui-courses.view-settings` ("Settings (Courses): Can view course settings") but not
`ui-courses.maintain-settings` ("Settings (Courses): Can create, edit and delete course settings"), the **New** button is no longer displayed at the top of the settings pages for Terms, Course types, Course departments, Processing statuses and Copryright types.
(Previously the button was displayed, and it was possible to enter the details of a new object -- but of course the actual creation of the object failed, rightly.)
=> [UICR-195] Omit nonfunctional "Add" buttons in settings

CHANGELOG.md, src/components/ViewCourse/sections/ViewCourseReserves.js
When a user clicks on a malformed "URL/PDF link" field (usually one with no scheme specified), we previously allowed the browser to go ahead and treat it as a relative URL, resulting in trying to displaying a course whose ID is the malformed URL. We now catch such cases and guess that the links were meant to be HTTPS.
=> [UICR-184] Do not link to non-existent course on a bad URL

CHANGELOG.md, package.json
This allows the last-edited metadata header to be displayed when editing a course reserve.
=> [UICR-235] ui-courses.add-edit-items permission now contains users.collection.get
